FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install gcc libpq-dev -y
RUN apt-get install python3-dev python3-pip python3-venv python3-wheel -y

COPY practica_big_data_2019/requirements.txt /tmp/
COPY practica_big_data_2019/resources/web /opt/flask

RUN pip3 install wheel
RUN pip3 install -r /tmp/requirements.txt 

ENV PROJECT_HOME=/opt/flask

CMD cd /opt/flask && python3 predict_flask.py